### ISSUE TITLE
Enemy bombs can still apply effects to enemies

### ISSUE THREAD

**Issue by bandaloo** [bandaloo/proc-cave-game#75] opened 2020-02-13 17:33 UTC
It's kind of funny to see ice bombers keep freezing themselves but it's probably not ideal.

**Comment by jojonium** [comment] 2020-02-13 19:24
I can't reproduce this on my branch

**Comment by jojonium** [comment] 2020-02-14 00:45
Closing as invalid

**Closed by jojonium** 2020-02-14 00:45 UTC
Labels: invalid
